#!/usr/bin/env bash
set -e
COMMAND=$1
shift

case $COMMAND in

  babel-node)
    exec ./node_modules/.bin/babel-node --presets es2015,stage-0 "$@"
    ;;

  testsuite)
    set -x
    exec ./run babel-node testsuite/run.js
    ;;

  *)
    echo "Unknown command $COMMAND"
    ;;

esac
